# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hashdown}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Solomon White", "Christopher Redinger"]
  s.date = %q{2009-09-25}
  s.description = %q{hashdown is a super lightweight rails plugin that adds hash-style lookups and option lists (for generating dropdowns) to ActiveRecord models}
  s.email = %q{redinger@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "hashdown.gemspec",
     "init.rb",
     "lib/finder.rb",
     "lib/hashdown.rb",
     "lib/selectable.rb",
     "rails/init.rb",
     "spec/finder_spec.rb",
     "spec/fixtures/currencies.yml",
     "spec/fixtures/states.yml",
     "spec/selectable_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/redinger/hashdown}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{hash-style lookups and option lists}
  s.test_files = [
    "spec/finder_spec.rb",
     "spec/selectable_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end
